name: test

on:
  push:

defaults:
  run:
    shell: bash

env:
  KUURAN: ""
  TRUEE: "true"
  FALSEE: "false"

jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "${{ env.KUURAN }} ${{ env.KUURAN != true }}"
        run: echo ${{ env.KUURAN != true }}
      - name: "${{ env.TRUEE }} ${{ env.TRUEE != true }}"
        run: echo ${{ env.TRUEE != true }}
      - name: "${{ env.FALSEE }} ${{ env.FALSEE != true }}"
        run: echo ${{ env.FALSEE != true }}
