name: test

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  use-reusable-workflow:
    permissions:
      contents: read
      packages: read
      statuses: write
    uses: Hiroshiba/test_workflow_call/.github/workflows/shared.yml@main
    # with:
    #   name: ${{ github.repository }}
