name: test

on:
  push:

env:
  VERSION: "1.0.0"

defaults:
  run:
    shell: bash

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      is_true: "true"
      is_false: "false"
    steps:
      - name: a
        run: echo hoge

  build_and_deploy:
    needs: config
    runs-on: ubuntu-latest
    steps:
      - name: ${{ fromJson(needs.config.outputs) }}
        if: fromJson(needs.config.outputs.is_true)
        run: echo true

      - name: ${{ fromJson(needs.config.outputs) }}
        if: fromJson(needs.config.outputs.is_false)
        run: echo false
