name: test

on:
  push:

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      # macだった場合にgnusedをインストールする
      - name: Install gnused
        if: matrix.os == 'macos-latest'
        run: brew install gnused

      # gnusedをデフォルトのsedにする
      - name: Set gnused as default sed
        if: matrix.os == 'macos-latest'
        run: echo 'export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"' >> $GITHUB_ENV

      - run: which sed
