name: check test

on:
  push:
  workflow_dispatch:
    inputs:
      is_true:
        type: boolean
        required: false
        default: true
      is_false:
        type: boolean
        required: false
        default: false

defaults:
  run:
    shell: bash

jobs:
  bug-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
