name: check test

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
            # windows-2019,
            # windows-latest,
            # macos-12,
            # macos-14,
            # macos-latest,
            ubuntu-20.04,
            # ubuntu-22.04,
            # ubuntu-latest,
          ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # python 3.7をインストール
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.7

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
