name: test
on:
  push:
jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.3"
          architecture: "x64"
          cache: pip
