name: test
on:
  push:
jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      EXPECTED_VOICEVOX_CORE_VERSION: latest
    steps:
      - name: Get latest version
        if: ${{ env.EXPECTED_VOICEVOX_CORE_VERSION == 'latest' }}
        shell: bash
        run: |
          set -eux
          echo "EXPECTED_VOICEVOX_CORE_VERSION=$(curl -sSfI "https://github.com/VOICEVOX/voicevox_core/releases/latest"| grep "location:" | sed -e "s%location: https://github.com/VOICEVOX/voicevox_core/releases/tag/%%" | sed 's/\r//g')" >> "$GITHUB_ENV"
      - name: Check downloaded version
        shell: bash
        run: |
          set -eux
          echo "${{ env.EXPECTED_VOICEVOX_CORE_VERSION }}"
