name: check test

on:
  push:
  workflow_dispatch:
    inputs:
      is_true:
        type: boolean
        required: false
        default: true
      is_false:
        type: boolean
        required: false
        default: false

defaults:
  run:
    shell: bash

jobs:
  bug-run:
    runs-on: ubuntu-latest
    steps:
      - name: check github.event.inputs.is_true == 'true'
        if: github.event.inputs.is_true == 'true'
        run: echo dummy
      - name: check github.event.inputs.is_true == true
        if: github.event.inputs.is_true == true
        run: echo dummy
      - name: check !github.event.inputs.is_true
        if: ${{ !github.event.inputs.is_true }}
        run: echo dummy
      - name: check inputs.is_true == 'true'
        if: inputs.is_true == 'true'
        run: echo dummy
      - name: check inputs.is_true == true
        if: inputs.is_true == true
        run: echo dummy
      - name: check !inputs.is_true
        if: ${{ !inputs.is_true }}
        run: echo dummy

  actionlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Update ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
      - name: actionlint
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color

  # use-reusable-workflow:
  #   permissions:
  #     contents: read
  #     packages: read
  #     statuses: write
  #   uses: Hiroshiba/test_workflow_call/.github/workflows/shared.yml@main
  #   # with:
  #   #   super_linter_env_vars: |
  #   #     VALIDATE_PYTHON=false
  #   #     VALIDATE_PYTHON_BLACK=false
  #   #     VALIDATE_PYTHON_FLAKE8=false
  #   #     VALIDATE_PYTHON_ISORT=false
  #   #     VALIDATE_PYTHON_MYPY=false
  #   #     VALIDATE_PYTHON_PYLINT=false
