name: test

on:
  push:

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      # macだった場合にgnusedをインストールする
      - name: Install gnused
        if: matrix.os == 'macos-latest'
        run: |
          brew install gnu-sed
          # echo "/usr/local/opt/gnu-sed/libexec/gnubin" >> $GITHUB_PATH
          # bashrcに追記
          echo 'export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"' >> $HOME/.bashrc

      - run: which sed
        shell: bash -l {0}

      - run: which sed
        shell: bash
