name: check test

# on:
#   push:
defaults:
  run:
    shell: bash

# jobs:
#   # 全OSで実行lsしてwcで行数を数えるコードを叩いてみる
#   check:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         os: [ubuntu-latest, windows-latest, macos-latest]
#     steps:
#       - name: Run ls
#         run: ls
#       - name: Run wc
#         run: ls | wc -l
#       - name: Setup tmate session
#         uses: mxschmitt/action-tmate@v3

on:
  push:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      repo_url:
        type: string
        required: false
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "テストしたいタグ名"
        required: true
      repo_url:
        type: string
        description: "リポジトリのURL（省略可能）"
        required: false

env:
  REPO_URL: "https://github.com/VOICEVOX/voicevox_engine"
  VERSION: "0.19.0"
  # VERSION: "0.18.1"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-12

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
