name: test

on:
  push:

env:
  VERSION: "0.0.0"

defaults:
  run:
    shell: bash

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      deploy: ${{ env.VERSION != '0.0.0' }}
    steps:
      - name: a
        run: echo ${{ env.VERSION != '0.0.0' }}

  build_and_deploy:
    needs: config
    runs-on: ubuntu-latest
    steps:
      - name: Upload to Release
        if: needs.config.outputs.deploy == 'true'
        run: echo ===${{ needs.config.outputs.deploy }}===
