name: test

# on:
#   push:
#   pull_request:

on:
  workflow_dispatch:
    inputs:
      is_true:
        type: boolean
        required: false
        default: true
      is_false:
        type: boolean
        required: false
        default: false

defaults:
  run:
    shell: bash

jobs:
  bug-run:
    runs-on: ubuntu-latest
    steps:
      - name: github.event.inputs.is_true && 'trueっぽい' || 'falseっぽい' → ${{ github.event.inputs.is_true && 'trueっぽい' || 'falseっぽい' }}
        run: echo dummy
      - name: fromJson(github.event.inputs.is_true) && 'trueっぽい' || 'falseっぽい' → ${{ fromJson(github.event.inputs.is_true) && 'trueっぽい' || 'falseっぽい' }}
        run: echo dummy
      - name: inputs.is_true && 'trueっぽい' || 'falseっぽい' → ${{ inputs.is_true && 'trueっぽい' || 'falseっぽい' }}
        run: echo dummy
      - name: fromJson(inputs.is_true) && 'trueっぽい' || 'falseっぽい' → ${{ fromJson(inputs.is_true) && 'trueっぽい' || 'falseっぽい' }}
        run: echo dummy
      - name: github.event.inputs.is_false && 'trueっぽい' || 'falseっぽい' → ${{ github.event.inputs.is_false && 'trueっぽい' || 'falseっぽい' }}
        run: echo dummy
      - name: fromJson(github.event.inputs.is_false) && 'trueっぽい' || 'falseっぽい' → ${{ fromJson(github.event.inputs.is_false) && 'trueっぽい' || 'falseっぽい' }}
        run: echo dummy
      - name: inputs.is_false && 'trueっぽい' || 'falseっぽい' → ${{ inputs.is_false && 'trueっぽい' || 'falseっぽい' }}
        run: echo dummy
      - name: fromJson(inputs.is_false) && 'trueっぽい' || 'falseっぽい' → ${{ fromJson(inputs.is_false) && 'trueっぽい' || 'falseっぽい' }}
        run: echo dummy

  # use-reusable-workflow:
  #   permissions:
  #     contents: read
  #     packages: read
  #     statuses: write
  #   uses: Hiroshiba/test_workflow_call/.github/workflows/shared.yml@main
  #   # with:
  #   #   super_linter_env_vars: |
  #   #     VALIDATE_PYTHON=false
  #   #     VALIDATE_PYTHON_BLACK=false
  #   #     VALIDATE_PYTHON_FLAKE8=false
  #   #     VALIDATE_PYTHON_ISORT=false
  #   #     VALIDATE_PYTHON_MYPY=false
  #   #     VALIDATE_PYTHON_PYLINT=false
