name: check test

on:
  push:
defaults:
  run:
    shell: bash

jobs:
  # 全OSで実行lsしてwcで行数を数えるコードを叩いてみる
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Run ls
        run: ls
      - name: Run wc
        run: ls | wc -l
      - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
