name: test

on:
  push:

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        hoge: [1, 2, 3]
        # macosのときはgsed、それ以外はsedを使う
        include:
          [
            { os: macos-latest, sed: gsed },
            { os: [windows-latest, ubuntu-latest], sed: sed },
          ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      # macだった場合にgnusedをインストールする
      - name: Install gnused
        if: matrix.os == 'macos-latest'
        run: |
          brew install gnu-sed

      - run: which ${{ matrix.sed }}
