name: check test

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
            # windows-2019,
            # windows-latest,
            # macos-12,
            # macos-14,
            # macos-latest,
            ubuntu-20.04,
            # ubuntu-22.04,
            # ubuntu-latest,
          ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
