name: test
on:
  push:
jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: windows-2022
    env:
      EXPECTED_VOICEVOX_CORE_VERSION: latest
    steps:
      - name: Get latest version
        if: ${{ env.EXPECTED_VOICEVOX_CORE_VERSION == 'latest' }}
        shell: bash
        run: |
          echo "EXPECTED_VOICEVOX_CORE_VERSION=$(gh release view --repo VOICEVOX/voicevox_core --json version | jq -r '.version')" >> "$GITHUB_ENV"
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Check downloaded version
        shell: bash
        run: |
          echo "${{ env.EXPECTED_VOICEVOX_CORE_VERSION }}"
