name: test

on:
  push:

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  test:
    strategy:
      matrix:
        os: [macos-11]
        hoge: [1, 2, 3]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install GNU coreutils
        shell: bash
        run: |
          brew install gnu-sed coreutils
          echo 'export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"' >> $HOME/.bashrc
          echo 'export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"' >> $HOME/.bashrc

      - name: Setup Python
        uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0 # v4.6.1
        with:
          python-version: "3.11.3"
          architecture: "x64"

      - run: which split
      - run: pip install -r requirements.txt
      - run: python -c "import pyopenjtalk"
