name: check test

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          [
            windows-2019,
            windows-2022,
            windows-2025,
            windows-latest,
            windows-11-arm,
            macos-13,
            macos-14,
            macos-15,
            macos-latest,
            ubuntu-20.04,
            ubuntu-22.04,
            ubuntu-24.04,
            ubuntu-latest,
            ubuntu-22.04-arm,
            ubuntu-24.04-arm,
          ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

      - run: |
          echo "OS: ${{ matrix.os }}"
          echo "\$OS: $OS"
          echo "runner.os: ${{ runner.os }}"
          echo "ImageOS: $ImageOS"
