name: test

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  use-reusable-workflow:
    uses: Hiroshiba/test_workflow_call/.github/workflows/shared.yml@main
    # with:
    #   name: ${{ github.repository }}
