name: check test

on:
  push:
  workflow_dispatch:
    inputs:
      is_true:
        type: boolean
        required: false
        default: true
      is_false:
        type: boolean
        required: false
        default: false

defaults:
  run:
    shell: bash

jobs:
  check:
    runs-on:
      - ubuntu-latest
      - windows-latest
      - macos-latest
    steps:
      - name: lsしてwcで行数を数えるコードを叩いてみる
        run: |
          set -eux
          ls
          echo "---"
          ls | wc -l

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
