name: test

on:
  push:

defaults:
  run:
    shell: bash

env:
  KUURAN: ""
  TRUEE: "true"
  FALSEE: "false"

jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - name: ${{ !!env.KUURAN }}
        run: ${{ !!env.KUURAN }}
      - name: ${{ !!env.TRUEE }}
        run: ${{ !!env.TRUEE }}
      - name: ${{ !!env.FALSEE }}
        run: ${{ !!env.FALSEE }}