name: check test

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  # 全OSで実行lsしてwcで行数を数えるコードを叩いてみる
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

      - name: Set alias and use curl
        run: |
          alias curl='curl --retry 3 --retry-delay 5 --retry-all-errors'
          curl https://example.com
